### ISSUE TITLE
Adding final bibliography with all the entries in chapterbib

### ISSUE THREAD

**Issue by SebastianoF** [habi/latex#1]
Thanks!
It worked for each chapter.
How to add a final bibliography with all the references at the end?
If running the main file with the bibliography added it returns an `illegal command`, noticing that the bibdata is already initialised.

**Comment by habi** [comment]
'Unfortunately' I switched to `biblatex` a while ago, so cannot really give you a working answer.
I suggest you look at [this answer here on tex.SE](https://tex.stackexchange.com/a/390639/828) which should give you what you want, with more modern tools...

**Comment by habi** [comment]
BTW, if I add 
```
\bibliographystyle{plainnat}
\bibliography{xampl}
\nocite{*}
```
just before the ending `\end{document}` on the (updated today) main.tex, then I get a bunch of compilation errors/warnings, but the end result seems to be what you ask.

**Comment by SebastianoF** [comment]
Thanks for the help, I found as well a solution that works with biber [here](https://tex.stackexchange.com/questions/202281/multiple-bibliographies-one-for-each-chapter-with-biblatex)

**Comment by habi** [comment]
Great, so I'm closing this issue...
